### ISSUE TITLE
Add a proposal draft for the natural language syntax

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/oekg#12]
Example files:
https://github.com/OpenEnergyPlatform/oekg/tree/proposal/draft/proposals/DevKopSys

**Comment by stap-m** [comment]
@Ludee in the OEO repo, we try to use more informative issue headings, that can be read as a continuation of sentence "The issue is about...". I'd recommend to do that here aswell 😉

**Comment by Ludee** [comment]
Thanks for pointing this out. It was an example issue to start the collaborative workflow for the repo. 
We created a branch with the proposal for a natural language syntax.
This issue should start the workflow:
Issue->Branch->PR
