### ISSUE TITLE
[SFS] Cannot delete contact person for factsheet

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oekg#20]
## Description of the issue

I added a contact person for the factsheet which is incorrect, but I can not delete it, I can only edit it (equal to giving the same instance a new label I think).

## Ideas of solution

Add a delete from field button in the edit field, to remove a wrong contact person from the field "who is the contact person for this factsheet" , but not delete the contact person as such. 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by christian-rli** [comment]
I can confirm this issue. It is also possible to add the same person several times in this way and to add names to the dataset that are not added in the drop down list. It's unclear to me what is merely a label and what is actually instantiated.

**Comment by christian-rli** [comment]
I found out, that the contact can be deleted. When the mouse hovers over the input field a ✕ symbol appears and that deletes the input. Such a symbol in the field below may be more intuitive. It's remains true that a contact cannot be deleted from the selection list.

**Comment by han-f** [comment]
I tried it again. I added information, a blue message on the bottom indicated this would be saved when saving. I clicked the green save button and nothing happened. Well, at least no success message appeared after clicking the button.
When I used the back arrow on the top left to get back to the overview, a message in green said it saved the sheet. I could not reproduce this a second time. The second time it took a minute or so after clicking the save button for the message to appear. So it seems to work in Firefox Windows, albeit with a delay.

But: it did not save my change. I deleted contact persons and then added only a single one (it was two before). After saving both appear again in the overview, also after refreshing the browser.

**Comment by han-f** [comment]
I tried it and this works. But it deletes all entries that were made. I think we need to have a functionality where we can delete individual entries from the input field.

**Comment by adelmemariani** [comment]
We can use checkboxes in the dropdowns to add entities to OEKG or remove entities from factsheets (but not the OEKG). Currently, only editing is possible via factsheets. Removing entities from OEKG is somehow risky, and we postponed the decision about entity removal to the future. Basically, we should decide who can remove from OEKG and via which interface.

**Comment by stap-m** [comment]
I think this is also solved. Access control is in progress.
