### ISSUE TITLE
[SFS] Format for "Date of publication" could be more intuitive

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oekg#22]
## Description of the issue
The format for date of publication is currently
MM/DD/YYYY

![grafik](https://user-images.githubusercontent.com/36844029/228228213-fcd5c7d2-1e1c-4259-907e-115ffedcb724.png)

I think the following would be more intuitive for users:
YYYY/MM/DD
or 
DD/MM/YYYY

## Ideas of solution
Change to one of the more intuitive formats

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by christian-rli** [comment]
In order to be completely ISO 8601 standard conformant, it should read YYYY-MM-DD. See also: https://xkcd.com/1179/

**Comment by adelmemariani** [comment]
Done! Please check it when the next version is released.
