### ISSUE TITLE
[FS Overview] Information that users think would be clickable is not clickable

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oekg#24]
## Description of the issue
The information displayed on the overview of a factsheet does not work as I would expect as a user. The information under input datasets and output datasets that is given looks like it should be clickable, so you would then see this information. There is no such functionality embedded.
### Factsheet
Scenario 

### Field
Input datasets, output datasets (but also all other fields that have a border drawn around them)
![grafik](https://user-images.githubusercontent.com/36844029/230277855-72299187-7156-4e06-9578-92374ea1d6ed.png)

## Ideas of solution
Describe possible addition in detail.

**Comment by adelmemariani** [comment]
@han-f Thank you for this feedback. They should be clickable.

I will work on this functionality, but it might not be available for the next release because, currently, I should work on other functionalities. I will return to this issue as soon as I finish other tasks.

**Comment by stap-m** [comment]
issue is outdated
