### ISSUE TITLE
[FS Overview] The factsheets overview page displays acronyms prominently, not the titles of the studies

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oekg#25]
## Description of the issue
On the overview the header for each factsheet is its acronym. I think it may be user friendlier (and look better) if it was the study name instead. 
![grafik](https://user-images.githubusercontent.com/36844029/230281949-3b61bbc6-c3c1-49bf-ad70-7a4bb8babea1.png)

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
@han-f Thanks a lot for this feedback. I will replace the acronym with the study name.  Please let me know if there should be other information. Currently, the fields are just examples, and we should determine what to include on the overview page.

**Comment by stap-m** [comment]
Already solved.
