### ISSUE TITLE
[SFS] Keywords and additional keywords list limited 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oekg#26]
## Description of the issue

There is a pre-defined list of keywords (study) and additional keywords (scenario). This list is rather limited and some studies or scenarios may not select any. If none is selected the "Keywords:" still shows on the factsheet overview, with no content followed. This may appear as if the users did not bother to provide keywords. I would like to suggest to either not shows "Keywords:" on the overview if none were supplied or to think about how we can better implement the possibility to provide keywords. 

## Ideas of solution
1) not show "Keywords:" at all when no entries are available
2) allow users to choose from a richer list of keywords 
3) allow users to add their own keywords

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by stap-m** [comment]
Thanks for the issue. Are the proposed suggestions exclusive or should they be combined?
* Regarding option 1: should there me an option "none" if no keywords should be added?
* Regarding option 2: Please feel free to suggest more keywords.
* We should discuss option 3 with caution. Is it really required for the factsheets or can we find a cleaner solution? For example: how could we implement a procedure to propose new keywords to the OEKG/OEO?

**Comment by stap-m** [comment]
This issue is related to #19

**Comment by u-mueller** [comment]
Long lists of keywords are the opposite of user friendliness, and suggesting new keywords should be as easy as possible, but I see the point. Maybe we discuss this at the OEKG-Dev meeting tomorrow or on our PM.

**Comment by stap-m** [comment]
EDIT: Notes from SIROP project meeting 2023-04-06:

Distinguish into two cases: 
    1. missing in factsheet but available in OEO 
         - add OEO autocomplete descriptors
         - define list of OEO autocomplete descriptors #19
    2. missing in factsheet and OEO
         - guide people through workflow that adds term to the ontology (complicated future work)
         - intermediate solution: link to the github oeo new term issue template course in the tutorial section about how to request new oeo terms
         - once the composed module is there, give the opportunity to add composed terms

New developments on keywords/descriptors are adressed in #19, that include this issue. Therefore I close this issue now.
