### ISSUE TITLE
[FS Overview] Check box in Factsheet overview - what for?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oekg#27]
## Description of the issue
The factsheet index page which displays all factsheets has a checkbox on the bottom right corner (depending on screen size). This checkbox cannot be clicked (Windows, Firefox) and it is not clear what functionality it should have.

I assume it might in the future help to choose several factsheets for a comparison. 
### Factsheet
Overview
![grafik](https://user-images.githubusercontent.com/36844029/230317180-4405a5dd-4ed0-4e55-b07e-5c7eb5a1ac74.png)

### Field
Name of the field, see [Documentation](https://github.com/OpenEnergyPlatform/oekg/blob/production/docs/index.md)

## Ideas of solution
Delete checkbox as long as it does not come with functionality.

**Comment by adelmemariani** [comment]
Yes, your assumption is correct. The goal for the checkboxes is the comparison, but the checkboxes are disabled because this functionality is still under development. I should remove the checkboxes in the next update...

**Comment by stap-m** [comment]
This is outdated.
