### ISSUE TITLE
[SFS] Improve structure of checkbox categories

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oekg#28]
This comes from issue #19 

Our scenario includes the following technologies: PV, wind, biomass, biogas, solar thermal, heat pump, gas, coal, oil, CHP, electricity, gas, heat. As the non expert user I am, I would expect all of those to be keywords for our study/scenario, but I found it difficult to map them all with clarity and the impression that I need to sort of split them into those categories is an additional factor of confusion for me. 
- sector
- energy carriers
- energy transformation process
- all of the above

I realize that this is a complex task, but ideally the interface would guide the user to differentiate the categories above or auto-suggestion related fields. 

_Originally posted by @christian-rli in https://github.com/OpenEnergyPlatform/oekg/issues/19#issuecomment-1497144564_

**Comment by stap-m** [comment]
@han-f @l-emele @Ludee @u-mueller your feedback would be helpful here. 
Do you face a similar confusion? Can you provide ideas for a better structure/interface?

**Comment by u-mueller** [comment]
Can't we - for the keywords - use auto-suggestions from the OEO excluding those terms from the checkboxes in the sector, energy carriers and energy transformation processes sections?

**Comment by stap-m** [comment]
We have now #43 which suggests a structure for this topic. Hence, I close.
