### ISSUE TITLE
[SFS] Editing existing persons and institutions should show existing information

### ISSUE THREAD

**Issue by u-mueller** [OpenEnergyPlatform/oekg#29]
When editing existing persons or institutions, e.g. just providing a new url, the existing information has to be retyped, otherwise it will be lost.

![Screenshot (76)](https://user-images.githubusercontent.com/113102700/231375558-7fd2d24a-35e4-4b79-9406-46fd835e55fb.png)

## Ideas of solution

Provide existing information in the fields of the editing box, so it won't be lost.

**Comment by adelmemariani** [comment]
@u-mueller Thanks for reporting this bug; I will fix it in the next release.

**Comment by stap-m** [comment]
I think this is also fixed.
