### ISSUE TITLE
[SFS] Develop a more guided process to enter information to factsheets

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oekg#32]
## Description of the issue

This comes from the OEKG meeting on 2023/04/13:

The ideas is to:
* Not show all information at once (reduce list at start)
* Do not show all "fields" at once (sector divisions, energy carrier ...)
* Divide them into modular steps (compare to the upload wizard https://openenergy-platform.org/dataedit/wizard/)
* The first draft should be done very fast with general information. Three levels: 
    1. Level 1 Beginner (Are there Energy Carriers? Yes/no)
    2. Level 2 Advances (Which energy carriers do you use? Gas, Coal, ..)
    3. Level 3 Expert Mode (Which energy carriers are modeled in detail? Hard Coal, Lignite...)

### Factsheet
Study / Scenario

### Field
Name of the field, see [Documentation](https://github.com/OpenEnergyPlatform/oekg/blob/production/docs/index.md)

**FS** | **Field** | **Level** | **New field required**| **Step**
---|---|---|---|---
Study | S1 - Name of study | 1 | -- | 1-1
Study | S2 - Acronym | 1 | -- | 1-2
Study | S3 - Institutions | 1 | -- | 1-3
Study | S4 - Funding source | 2 | -- |  2-1
Study | S5 - Research Question | 2 | -- | 2-2
Study | S6 - Contact person | 1 | -- | 1-4 
Study | S7: Sector divisions | 2 | -- | 2-3
Study | S8: Sectors | 2 | -- | 2-4
Study | S9-1:  | 1 | Are energy carriers and energy transformation processes represented in the study? (y/n) | 1-5
Study | S9-2: Energy carriers and energy transformation processes (highlevel) | 2 | restructure S9 and S10 | 2-5
Study | S9-3: Energy carriers and energy transformation processes (detailed) | 3 | restructure S9 and S10 | 3-1
Study | ~S10: Energy transformation processes~ | 3 | -- | 3-2
Study | S11: Keywords | 2 | -- | 2-5
Study | R1: Report Title | 1 | -- | 1-6
Study | R2 - Date | 2 | -- | 2-6
Study | R3 - DOI | 2 | -- | 2-7
Study | R4 - Place of publication | 2 | -- | 2-8
Study | R5 - Link | 1 | -- | 1-7
Study | R6 - Authors | 1 | -- | 1-8 
Study | A1 - Scenarios| level 1 | Have there been scenarios used or developed for the study? (y/n) | 1-9
Study | A2 - Scenarios| level 1 | Have energy system models or frameworks been used in the study? (y/n) | 1-10

**FS** | **Field** | **Level** | **New field required**| **Step**
---|---|---|---|---
Scenario | SC1 - Name of scenario | level 1 | -- | 1-1
Scenario | SC2 - Acronym | level 1 | -- | 1-2
Scenario | SC3 - Storyline | level 2 | -- | 2-1
Scenario | SC4 - Spatial regions | level 2 | -- | 2-2 
Scenario | SC5 - Interacting regions | level 2 | -- | 2-3 
Scenario | SC6 - Scenario year  | level 2 | -- | 2-4
Scenario | SC7: Keywords | level 2 | -- | 2-5
Scenario | SC8 - Input/output datasets | level 2 | -- | 2-6

## Ideas of solution
Describe possible addition in detail.

**Comment by stap-m** [comment]
I created two tables above to categorize the level of skills / detail for the fectsheets. The currently proposed order of questions is derived consequently.

I am wondering, how the different levels should be interweaving/separated from each other: e.g. we could ask questions like "do you want to give more detailed information on energy carriers? (y/n)" or we could let the users finish one level and then lead them to the next level. We should anyhow avoid the impression that doubled information has to be added, i.e. once at a high level and once in detail.

**Comment by jh-RLI** [comment]
I will talk to @bmlancien today and we will try to create basic mockups for the redesign. I will present them on the second day of the project meeting next week. I think it's worth considering a complete redesign. The current user interface looks very different from the rest of the OEP. However, we will focus on reworking the process of creating the factsheet, as suggested in this issue.

**Comment by u-mueller** [comment]
This also is related to OpenEnergyPlatform/oeplatform#1524: Maybe we should think of restructuring ´sector division´ and ´sector´ in the same way as proposed (and implemented) here.

**Comment by adelmemariani** [comment]
I divided the factsheets into different steps:

![Screenshot 2023-04-25 at 08 47 02](https://user-images.githubusercontent.com/7637364/234196025-d5559100-9701-4f98-a322-31fe21e27449.png)

Does it help to have a better UI?

**Comment by bmlancien** [comment]
Yes @adelmemariani, something divided into steps is a good idea, although it also has to be clear that they are optional. I'll create a mockup to help with the process.

**Comment by stap-m** [comment]
This is implemendet.
