### ISSUE TITLE
[SFS] Hyperlink to study reports

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oekg#34]
## Description of the issue

Link to study report is not implemented as hyperlink and thus not clickable

## Steps to Reproduce
![grafik](https://user-images.githubusercontent.com/36884905/236132449-9bd5d70f-c650-4ea4-8cdb-7d7fed6ce8a7.png)

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
@l-emele Thank you for reporting this bug. I will make it clickable.

Here is how it will look:
![Screenshot 2023-05-08 at 17 02 44](https://user-images.githubusercontent.com/7637364/236859793-661eb6f5-90dc-4fcb-80a1-86620dde2675.png)

**Comment by adelmemariani** [comment]
The updates can be checked here: http://toep.iks.cs.ovgu.de/factsheet/fs/71ee99be-d811-6fc8-0707-f5dea0485529
I think we could close this issue.

**Comment by l-emele** [comment]
I agree and close.
