### ISSUE TITLE
[SFS] Date of publication contains too much detail

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oekg#35]
## Description of the issue

Date of publication is shown as time stamp including hours, minutes and seconds but it should only be a date

## Steps to Reproduce
![grafik](https://user-images.githubusercontent.com/36884905/236132846-55ff3c44-21d0-485e-9911-0ad68c3fea30.png)
## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
@l-emele Thank you for suggesting this. I trimmed the date. This will be seen in the next (major) release.

Here is how it will look:
![Screenshot 2023-05-08 at 17 02 48](https://user-images.githubusercontent.com/7637364/236859603-81ef375a-fdbb-454e-98a8-3c81e3ffb278.png)

**Comment by adelmemariani** [comment]
The updates can be checked here: http://toep.iks.cs.ovgu.de/factsheet/fs/71ee99be-d811-6fc8-0707-f5dea0485529
I think we could close this issue.

**Comment by l-emele** [comment]
I agree and close.
