### ISSUE TITLE
Comparison Tool Interface Needs to Guide Users to Possible Comparisons

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oekg#41]
## Description of the issue

This issue was discussed in the OEKG dev meeting. As we develop the scenario comparson tool, we need to consider the fact that at first there will only be very few annotated scenarios in the knowledge graph. Currently we're planning to offer a lot of possible selections to enable comparison. The user experience would suffer greatly if it's not always clear at first sight where actually possible comparisons can be found. 

## Ideas of solution

Show highlight fields that would allow possible comparisons. Or show example comparisons.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
Thanks, @christian-rli, for highlighting this point. I made the following workflow. How is it?

After selecting the scenarios, we should choose the aspects of the comparisons. Then we can drag and drop scenarios on the comparison page to choose the base and the comparing scenarios:


https://github.com/OpenEnergyPlatform/oekg/assets/7637364/fda3a4a4-ac0b-45ba-86ba-cba3368f82ec

**Comment by stap-m** [comment]
@adelmemariani Thanks for the workflow. 
I have a change request. When selecting the scenarios (sec 3ff in the video), we can not expect the users to know what "AMS", "KS80" ect mean and how they differ. That is why I think more information is needed, e.g. by showing also the full scenario name or mouse over the description, maybe more. toep is not available at the moment, but I can suggest the needed information later.

**Comment by stap-m** [comment]
One step before, when selecting criteria, it would also be nice to show, how many scenarios are "left" for comparison when clicking or unclicking criteria. Is that possible? That is how I understood the purpose of this issue.

**Comment by adelmemariani** [comment]
> @adelmemariani Thanks for the workflow. I have a change request. When selecting the scenarios (sec 3ff in the video), we can not expect the users to know what "AMS", "KS80" ect mean and how they differ. That is why I think more information is needed, e.g. by showing also the full scenario name or mouse over the description, maybe more. toep is not available at the moment, but I can suggest the needed information later.

I released a new version on toep, and in this version, more information about scenarios is given on mouseover. Also scenario comparison with color-coding is available.
