### ISSUE TITLE
[SFS] Restructure / dissolve section "energy carriers" and "energy transformation"

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/oekg#43]
## Description of the issue

As discussed before, the structure of the oeo for `energy carriers` and `energy transformations` does not sufficiently satisfy the requirements to describe a study/scenario. 
This initiated a restructuring of `energy transformation` hierarchy, which is worthwile anyway.
 
![grafik](https://github.com/OpenEnergyPlatform/oekg/assets/38690039/614fb3f5-f499-4b61-b566-315b0bae7efd)

However, further feedback on factsheet part of `energy carriers` and `energy transformations` gave, that user / modellers have rather a concept of "technologies" in mind, when they want to describe their study. "Technology" as generalized term (and provider of a proper hierarchy) is not part of the oeo. The entities that users mean by "technologies" are, though, yet kinf of scattered around the oeo.

With a little OEO jigsaw here comes a proposal that focuses on this "technology perspective" and hopefully satisfies better the user requirements. This section could replace the current energy carriersa ands transformation section of the factsheets.

Feedback on whether this structure improves the descriptiveness of studies and, in case, on further refinement is very much apprechieated 
@l-emele @ludee @u-mueller @han-f @christian-rli  Thanks!

FYI @adelmemariani @fabianneuhaus 

## Ideas of solution

| **main technology topics** | **subtopics** | **specification, if needed** |
| --- | --- | --- |
| power generation               | wind power plant                           | wind farm subclasses                             |
|  | solar power plant                          | subclasses w/o hierarchy                         |
|  | Geothermal power plant                     |                                                  |
|  | hydro power plant                          | subclasses w hierarchy                           |
|  | fueled power plants                        | energy carriers of fueled power plant subclasses |
|  (cogeneration) | CHP                                        | energy carriers of fueled power plant subclasses |
| heat generation                | Geothermal heat plant                      |                                                  |
|  | Solar thermal heat plant                   |                                                  |
|  | heat pump                                  |                                                  |
|  | combustion based heater                    |                                                  |
|  | Hybrid boiler                              |                                                  |
|  | P2Heat                                     |                                                  |
| Mobility                       | electric vehicle |  inferred hierarchy              |
|  | internal combustion vehicle | inferred hierarchy              |
|  | … what else?                               |                                                  |
| PtX                            |  | subclasses w hierarchy                           |
| storage                      |  | energy storage object subclasses (curated) |
| non-energetic demand for fuels | | fuel subclasses          |

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by l-emele** [comment]
After thinking a bit about this issue I think it is a viable solution and to me it does not look like an alternative to the  `energy carriers` and `energy transformations` approach, but more like an extension or refinement of that discussion.

Looking at the table I think, there are three distinctive parts: a process, an artificial object and energy carriers, but in some cases  parts of that are not necessarily be shown to the users of the fact sheets.

Anyway, this understanding of technology is very different from our current definition of technology thus we needs a redefinition. I'll open an issue for that in the oeo repo.

**Comment by l-emele** [comment]
We have now the solution with the technology classes. So I think we can close this issue.
