### ISSUE TITLE
`DC:contributor` used improperly

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenEnergyPlatform/oekg#9]
https://github.com/OpenEnergyPlatform/oekg/blob/main/OEKG_in_Turtle/OEKG_With_Datasets.ttl#L9
`OEKG:Ludwig_Hulk DC:type DC:contributor .`

But `DC:contributor` is a property, so it cannot be used this way.
You can say that person is a `schema:Person`

**Comment by adelmemariani** [comment]
@VladimirAlexiev Thank you so much for reporting this. You are right, It is a bug and it is related to the way I populated the knowledge graph. I will fix it. The OEKG is under development and might contain bugs like the above. We plan to have some principled ways to evaluate the knowledge graph (i.e logical consistency checks and ...).

**Comment by l-emele** [comment]
We also have `oeo:person`.

**Comment by VladimirAlexiev** [comment]
@l-emele I don't see `oeo:person` but classes should be Uppercase, and it's better to reuse rather than define your own "Person" class.

**Comment by l-emele** [comment]
@VladimirAlexiev : With `oeo:person` I meant the class `person` in the Open Energy Ontology: http://openenergy-platform.org/ontology/oeo/OEO_00000323

Please be aware, that we are still in a very early stage of the knowledge graph.
